### ISSUE TITLE
Is it possible to use next available port?

### ISSUE THREAD

**Issue by gaearon** [node-modules/detect-port#15]
Before updating to 1.1.0, `detect-port` used to suggest the next available port (e.g. 3001 if I requested 3000 but it is busy). Now, it seems to always suggest random ports (e.g. I just got 49655).

Is it possible to preserve the old behavior of suggesting the next available port, or are there any downsides?

**Comment by fengmk2** [comment]
OK, I will make it try to get next port 10 times.

**Comment by fengmk2** [comment]
@gaearon Please take a try on detect-port@1.1.1
