### ISSUE TITLE
Library not detecting port is in use

### ISSUE THREAD

**Issue by KyleAMathews** [node-modules/detect-port#17]
I'm using this lib with Gatsby having borrowed the idea from create-react-app. It had been working great but it's now for whatever reason not detecting used ports.

I start a gatsby instance on port 8000 and then another and detect-port tells me 8000 is open but when gatsby tries starting in the second instance, it gets an `EADDRINUSE`.

I've tried this on node 6 and 7.

Does it matter that Gatsby is listening on 0.0.0.0?

**Comment by KyleAMathews** [comment]
Oh and I'm on a macOS Sierra 10.12.3

**Comment by egoist** [comment]
I met the same issue while I run my project on `localhost`

**Comment by sorrycc** [comment]
I got the same issue, and detect-port@1.0.x works.

**Comment by fengmk2** [comment]
Maybe bug here, I will check it and fix it today.

**Comment by d4rkr00t** [comment]
Bug is actually here https://github.com/node-modules/detect-port/blob/master/lib/detect-port.js#L47

I fixed it in my project like this: https://github.com/d4rkr00t/aik/blob/master/src/utils/detect-port.js#L12

Basically you need to specify a host.
