### ISSUE TITLE
Add ability to specify a hostname

### ISSUE THREAD

**Issue by Timer** [node-modules/detect-port#19]
Right now, [there is no way to specify a hostname.](https://github.com/node-modules/detect-port/blob/master/lib/detect-port.js#L47)
This means `detect-port` is only useful when listening to the default binding address (`::`, `0.0.0.0`).

It would be great if we could optionally pass a hostname, [just like the Node API](https://nodejs.org/api/net.html#net_server_listen_port_hostname_backlog_callback).

**Comment by fengmk2** [comment]
Yes, we can follow the Node API. I will send a pull request this week.

**Comment by fengmk2** [comment]
It's a bug https://github.com/node-modules/detect-port/issues/17

**Comment by Timer** [comment]
Hi! This didn't fix the issue. It'd be great if we could actually pass the hostname to check explicitly.

**Comment by fengmk2** [comment]
OK

**Comment by Timer** [comment]
I'll add a bit more information for posterity: effectively, we might bind to `abc.local` which isn't covered by checking `::`, `localhost`, and the current public IP.

In our exact case, we're binding to `0.0.0.0` (for example), but not passing a host name to the node API binds to `::` which ALSO works when visiting `0.0.0.0`. We could keep adding cases for these addresses but at some point it will start falling apart when we use custom addresses (like `abc.local` which resolves to some random address).

At the end of the day, I'd love to be able to just tell `detect-port` what address I'd like to check for port availability on. I still believe checking the other hosts (`::`, `0.0.0.0`, `localhost`, etc) is still beneficial because it's confusing to have two different applications running on `127.0.0.1` and `0.0.0.0` but using the same port.

**Comment by xudafeng** [comment]
https://github.com/node-modules/detect-port/pull/26
