### ISSUE TITLE
Does not work on windows' git bash

### ISSUE THREAD

**Issue by viankakrisna** [node-modules/detect-port#27]
Steps to reproduce:

1. Install git bash for windows
2. run an app on port 3000
3. run detect-port on port 3000
![screenshot_37](https://user-images.githubusercontent.com/9636410/29301491-b6a27c46-81a6-11e7-90ee-743542c79a67.png)

**Comment by fengmk2** [comment]
> Something is already running on port 3000

Your snapshot show out the port 3000 is not available.

**Comment by viankakrisna** [comment]
I've posted the issue in the wrong repo, sorry!
