### ISSUE TITLE
无论哪个端口都被探测到已被占用,例如8989，进程中查询不到

### ISSUE THREAD

**Issue by zxm20160516** [node-modules/detect-port#30]
mac，之前8989端口是好的，现在探测都被占用，1.1.3版本，求助。facebook官方create-react-app搭建的工程(之前好像是没有关闭服务，重启了电脑)

**Comment by xudafeng** [comment]
@zxm20160516

```bash
$ cat /etc/hosts
```

看下host绑定是否有问题呢

```
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
```

**Comment by fengmk2** [comment]
@xudafeng 没有绑定 localhost 的问题也解决了的。

**Comment by fengmk2** [comment]
create-react-app  创建出来的 app 使用的模块是 detect-port-alt，它的源代码不是指向我们这里的。
