### ISSUE TITLE
A problem with an installation via NPM

### ISSUE THREAD

**Issue by klimcode** [node-modules/detect-port#31]
Hi.
I don't know where to write about this problem. Hope, you know how to solve it.
I try to install "detect-port-alt" via NMP but it fails always.
No another package has this problem.
```
21645 verbose stack Error: ENOENT: no such file or directory, chmod '/mnt/storage/all/work/libraries/benchmark-react/node_modules/detect-port-alt/bin/detect-port'
21646 verbose cwd /mnt/storage/all/work/libraries/benchmark-react
21647 verbose Linux 4.13.0-36-generic
21648 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
21649 verbose node v9.2.0
21650 verbose npm  v5.7.1
21651 error path /mnt/storage/all/work/libraries/benchmark-react/node_modules/detect-port-alt/bin/detect-port
21652 error code ENOENT
21653 error errno -2
21654 error syscall chmod
21655 error enoent ENOENT: no such file or directory, chmod '/mnt/storage/all/work/libraries/benchmark-react/node_modules/detect-port-alt/bin/detect-port'
21656 error enoent This is related to npm not being able to find a file.
21657 verbose exit [ -2, true ]
```

**Comment by denghongcai** [comment]
https://github.com/npm/npm/issues/9633 seems related to this issue?

**Comment by jkriss** [comment]
I'm seeing the same thing on Ubuntu 16.04 (node 9.8.0 and npm 5.6.0) although it works fine on Mac OS.

**Comment by klimcode** [comment]
The problem does not appear with Yarn. So, I have to use it with create-react-app.

**Comment by rajohns08** [comment]
I'm seeing the same issue on linux

**Comment by ketysek** [comment]
Also seeing the issue in node:8 docker image.

**Comment by 0xc0d3r** [comment]
Hey! I'm using https://github.com/zeit/serve library and it has a dependency on `detect-port` lib. I'm also getting the error in only docker image and my node version is `v8.11.3` as said by @ketysek. Did anyone solve the problem?

**Comment by ketysek** [comment]
@0xc0d3r yes, I've switched to yarn.

**Comment by snackCake** [comment]
I'm also seeing this problem after running create-react-app and running in Docker (node:8.11.3).

**Comment by abdelbolanos-cbc** [comment]
Hi, I just have the same issue in node 8.9.4 and I notice that my `package-lock.json` was causing it. Try to remove it (or rename it) and try again `npm install`. Good luck!!!

**Comment by stratease** [comment]
I'd recommend trying `npm i --no-bin-links` - this fixed our situation.

**Comment by zearg** [comment]
I'd this bug.
**Solved** : Be sure there is no `package-lock.json` in folder you type the command

**Comment by stewartmatheson** [comment]
> I'd this bug.
> **Solved** : Be sure there is no `package-lock.json` in folder you type the command

I tried this and got the same issue. Regardless I'm not sure some people can simply delete their package lock file as it may break some compatibility between other modules.

**Comment by a2chan** [comment]
I think this has something to do with the file system in which it is being installed. I switched from my Windows ntfs to Linux ext4 and the installation went smoothly.
