### ISSUE TITLE
Upgrade debug dependency to 4.3.1+

### ISSUE THREAD

**Issue by apupier** [node-modules/detect-port#44]
Currently 2.6.0 specified https://github.com/node-modules/detect-port/blob/f35409d53f9298a60e2c6c1560f42ea182025dd4/package.json#L25

but `npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)`

**Comment by xudafeng** [comment]
https://github.com/node-modules/detect-port/pull/46
