### ISSUE TITLE
Warnings displayed when running detect-port

### ISSUE THREAD

**Issue by PhiLhoSoft** [node-modules/detect-port#48]
After upgrading to detect-port v. 1.5.0 (and I see the same issue with 1.4.0), I get the following messages:

```
> ng serve main --port `detect 8080`

C:\xxx\node_modules\.bin/../detect-port/bin/detect-port.js: line 1: use strict: command not found
C:\xxx\node_modules\.bin/../detect-port/bin/detect-port.js: line 3: syntax error near unexpected token `('
C:\xxx\node_modules\.bin/../detect-port/bin/detect-port.js: line 3: `const pkg = require('../package');'
```
Running an Angular project on Windows 10.

I reverted to 1.3.0 which works fine for my purposes.

Side notes: the HISTORY file doesn't list the 1.4.0 version. And the Releases side panel on the main page still lists the 1.2.0 release… (I have no idea how this is updated.)

**Comment by fengmk2** [comment]
Revert to detect-port@1.4.1 now.
https://github.com/node-modules/detect-port/pull/46

**Comment by xudafeng** [comment]
fixed with https://github.com/node-modules/detect-port/pull/49

@PhiLhoSoft
