### ISSUE TITLE
使用 detect-port 校验

### ISSUE THREAD

**Issue by LuckyFBB** [node-modules/detect-port#57]
node: 18.20.4

占用 8080 端口
```test.js
const net = require('net');

const server = new net.Server();

server.listen(8080, '127.0.0.1', () => {
  console.log('start at 127.0.0.1');
});
```

使用 detect-port 当前端口是否被占用，输出 `port: 8080 was not occupied`
```detect.js
const port = 8080;

detect(port)
  .then(_port => {
    if (port == _port) {
      console.log(`port: ${port} was not occupied`);
    } else {
      console.log(`port: ${port} was occupied, try port: ${_port}`);
    }
  })
  .catch(err => {
    console.log(err);
  });
```

上述代码在node@16.x运行不会有问题，占用 8080 端口之后，再次执行`detect.js`会输出`port: 8080 was occupied, try port: 8081`

导致这个问题是否和 node@18.x 的 DNS 解析有关系?

**Comment by fengmk2** [comment]
使用  2.0.0 版本这个问题应该修复了

**Comment by LuckyFBB** [comment]
> 使用 2.0.0 版本这个问题应该修复了

使用了新的 detect-port@2.0.1，直接抛出了异常
<img width="658" alt="image" src="https://github.com/user-attachments/assets/c823071c-48ad-423b-a171-823d3c86c0e3">

**Comment by fengmk2** [comment]
foo.js 我写了一个脚本，没有发现问题？

```bash
node foo.js

start at 127.0.0.1
_port 8080
port: 8080 was not occupied
```

```js
const net = require('net');
const { detectPort: detect } = require('detect-port');

const server = new net.Server();

server.listen(8080, '127.0.0.1', () => {
  console.log('start at 127.0.0.1');


  const port = 8080;

  detect(port)
    .then(_port => {
      console.log('_port', _port);
      if (port === _port) {
        console.log(`port: ${port} was not occupied`);
      } else {
        console.log(`port: ${port} was occupied, try port: ${_port}`);
      }
    })
    .catch(err => {
      console.log(err);
    });
});
```

**Comment by LuckyFBB** [comment]
> foo.js 我写了一个脚本，没有发现问题？
> 
> ```shell
> node foo.js
> 
> start at 127.0.0.1
> _port 8080
> port: 8080 was not occupied
> ```
> 
> ```js
> const net = require('net');
> const { detectPort: detect } = require('detect-port');
> 
> const server = new net.Server();
> 
> server.listen(8080, '127.0.0.1', () => {
>   console.log('start at 127.0.0.1');
> 
> 
>   const port = 8080;
> 
>   detect(port)
>     .then(_port => {
>       console.log('_port', _port);
>       if (port === _port) {
>         console.log(`port: ${port} was not occupied`);
>       } else {
>         console.log(`port: ${port} was occupied, try port: ${_port}`);
>       }
>     })
>     .catch(err => {
>       console.log(err);
>     });
> });
> ```

不好意思，是我的代码写得有问题😅

**Comment by LuckyFBB** [comment]
不好意思，应该是另一个问题。写在两个文件里面，分别运行。
```js
// foo.js
const net = require('net');

const server = new net.Server();

server.listen(8080, '127.0.0.1', () => {
  console.log('start at 127.0.0.1:8080');
});
```
运行 foo.js 占用 8080 端口

```js
// index.js
const { detectPort: detect } = require('detect-port');
const port = 8080;

detect(port)
  .then(_port => {
    console.log('_port', _port);
    if (port === _port) {
      console.log(`port: ${port} was not occupied`);
    } else {
      console.log(`port: ${port} was occupied, try port: ${_port}`);
    }
  })
  .catch(err => {
    console.log(err);
  });
```
运行 index.js 文件，输出`port: 8080 was not occupied`

在node18下
<img width="822" alt="image" src="https://github.com/user-attachments/assets/9e260acf-b65a-45d5-917a-06ad4acebe9a">

在node16下
<img width="780" alt="image" src="https://github.com/user-attachments/assets/f61f2980-9c49-4515-b62a-05d83c6f411c">

**Comment by fengmk2** [comment]
加上 debug 日志运行，我发现了一个 bug，node >= 18 对于 localhost 解析的地址不是 127.0.0.1

```bash
NODE_DEBUG=detect* node index.cjs

DETECT-PORT 97545: detect free port between [8080, 8090)
DETECT-PORT 97545: try listen 8080 on undefined
DETECT-PORT 97545: get free undefined:8080
DETECT-PORT 97545: try listen 8080 on 0.0.0.0
DETECT-PORT 97545: get free 0.0.0.0:8080
DETECT-PORT 97545: try listen 8080 on localhost
DETECT-PORT 97545: get free localhost:8080
DETECT-PORT 97545: try listen 8080 on 30.230.57.2
DETECT-PORT 97545: get free 30.230.57.2:8080
_port 8080
port: 8080 was not occupied
```

**Comment by fengmk2** [comment]
@LuckyFBB 2.1.0 版本修复了这个问题
